<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Alumno;

class AlumnosSeeder extends Seeder
{
    public function run()
    {
        Alumno::create([
            'matricula' => 'B001',
            'nombre' => 'Carlos',
            'apellidopaterno' => 'Rodríguez',
            'apellidomaterno' => 'Martínez',
            'correo' => 'carlos.rodriguez@mail.com',
            'nivel_educativo_id' => 1,
            'grado_id' => 1,
            'seccion' => 'B',
            'fecha_inscripcion' => '2023-09-01',
            'contacto1nombre' => 'Laura Rodríguez',
            'telefono1' => '9876543210',
            'correo_familia' => 'laura.rodriguez.familia@mail.com',
            'contacto2nombre' => 'José Martínez',
            'telefono2' => '1234567890',
            'usuario_classroom' => 'carlos.rodriguez@classroom.com',
            'contraseña_classroom' => 'Csl$Carlos2023',
            'usuario_moodle' => 'carlos.rodriguez@moodle.com',
            'contraseña_moodle' => 'B001',
            'usuario_mathletics' => 'carlos.rodriguez@mathletics.com',
            'contraseña_mathletics' => 'Math$2023',
            'usuario_hmh' => 'carlos.rodriguez@hmh.com',
            'contraseña_hmh' => 'HMH$2023',
            'usuario_progrentis' => 'carlos.rodriguez@progrentis.com',
            'contraseña_progrentis' => 'Progrentis$2023',
            'plataforma_id' => 1,
        ]);

        Alumno::create([
            'matricula' => 'B002',
            'nombre' => 'Ana',
            'apellidopaterno' => 'González',
            'apellidomaterno' => 'Pérez',
            'correo' => 'ana.gonzalez@mail.com',
            'nivel_educativo_id' => 2,
            'grado_id' => 1,
            'seccion' => 'A',
            'fecha_inscripcion' => '2023-09-02',
            'contacto1nombre' => 'Roberto González',
            'telefono1' => '2345678901',
            'correo_familia' => 'roberto.gonzalez.familia@mail.com',
            'contacto2nombre' => 'María Pérez',
            'telefono2' => '3456789012',
            'usuario_classroom' => 'ana.gonzalez@classroom.com',
            'contraseña_classroom' => 'Csl$Ana2023',
            'usuario_moodle' => 'ana.gonzalez@moodle.com',
            'contraseña_moodle' => 'B002',
            'usuario_mathletics' => 'ana.gonzalez@mathletics.com',
            'contraseña_mathletics' => 'Math$2023',
            'usuario_hmh' => 'ana.gonzalez@hmh.com',
            'contraseña_hmh' => 'HMH$2023',
            'usuario_progrentis' => 'ana.gonzalez@progrentis.com',
            'contraseña_progrentis' => 'Progrentis$2023',
            'plataforma_id' => 1,
        ]);

        Alumno::create([
            'matricula' => 'B003',
            'nombre' => 'Luis',
            'apellidopaterno' => 'Martínez',
            'apellidomaterno' => 'Sánchez',
            'correo' => 'luis.martinez@mail.com',
            'nivel_educativo_id' => 3,
            'grado_id' => 2,
            'seccion' => 'C',
            'fecha_inscripcion' => '2023-09-03',
            'contacto1nombre' => 'Elena Martínez',
            'telefono1' => '4567890123',
            'correo_familia' => 'elena.martinez.familia@mail.com',
            'contacto2nombre' => 'Carlos Sánchez',
            'telefono2' => '5678901234',
            'usuario_classroom' => 'luis.martinez@classroom.com',
            'contraseña_classroom' => 'Csl$Luis2023',
            'usuario_moodle' => 'luis.martinez@moodle.com',
            'contraseña_moodle' => 'B003',
            'usuario_mathletics' => 'luis.martinez@mathletics.com',
            'contraseña_mathletics' => 'Math$2023',
            'usuario_hmh' => 'luis.martinez@hmh.com',
            'contraseña_hmh' => 'HMH$2023',
            'usuario_progrentis' => 'luis.martinez@progrentis.com',
            'contraseña_progrentis' => 'Progrentis$2023',
            'plataforma_id' => 1,
        ]);

        Alumno::create([
            'matricula' => 'B004',
            'nombre' => 'Marta',
            'apellidopaterno' => 'Fernández',
            'apellidomaterno' => 'López',
            'correo' => 'marta.fernandez@mail.com',
            'nivel_educativo_id' => 1,
            'grado_id' => 2,
            'seccion' => 'B',
            'fecha_inscripcion' => '2023-09-04',
            'contacto1nombre' => 'Luis Fernández',
            'telefono1' => '6789012345',
            'correo_familia' => 'luis.fernandez.familia@mail.com',
            'contacto2nombre' => 'Ana López',
            'telefono2' => '7890123456',
            'usuario_classroom' => 'marta.fernandez@classroom.com',
            'contraseña_classroom' => 'Csl$Marta2023',
            'usuario_moodle' => 'marta.fernandez@moodle.com',
            'contraseña_moodle' => 'B004',
            'usuario_mathletics' => 'marta.fernandez@mathletics.com',
            'contraseña_mathletics' => 'Math$2023',
            'usuario_hmh' => 'marta.fernandez@hmh.com',
            'contraseña_hmh' => 'HMH$2023',
            'usuario_progrentis' => 'marta.fernandez@progrentis.com',
            'contraseña_progrentis' => 'Progrentis$2023',
            'plataforma_id' => 1,
        ]);

        Alumno::create([
            'matricula' => 'B005',
            'nombre' => 'José',
            'apellidopaterno' => 'García',
            'apellidomaterno' => 'Jiménez',
            'correo' => 'jose.garcia@mail.com',
            'nivel_educativo_id' => 2,
            'grado_id' => 3,
            'seccion' => 'A',
            'fecha_inscripcion' => '2023-09-05',
            'contacto1nombre' => 'Carmen García',
            'telefono1' => '8901234567',
            'correo_familia' => 'carmen.garcia.familia@mail.com',
            'contacto2nombre' => 'Juan Jiménez',
            'telefono2' => '9012345678',
            'usuario_classroom' => 'jose.garcia@classroom.com',
            'contraseña_classroom' => 'Csl$Jose2023',
            'usuario_moodle' => 'jose.garcia@moodle.com',
            'contraseña_moodle' => 'B005',
            'usuario_mathletics' => 'jose.garcia@mathletics.com',
            'contraseña_mathletics' => 'Math$2023',
            'usuario_hmh' => 'jose.garcia@hmh.com',
            'contraseña_hmh' => 'HMH$2023',
            'usuario_progrentis' => 'jose.garcia@progrentis.com',
            'contraseña_progrentis' => 'Progrentis$2023',
            'plataforma_id' => 1,
        ]);
    }
}
